#!/bin/bash

# Step 1: Update header.tex with the current directory to the images
echo "\\graphicspath{{$(pwd)/tex-pics/}}" > header.tex
cat header.template.tex >> header.tex

# Step 2: report current directory to have an absolute reference to header.tex
echo "texheader   := $(pwd)/header.tex" > makefile.chap.newtemplate
cat makefile.chap.template >> makefile.chap.newtemplate
echo "texheader   := $(pwd)/header.tex" > makefile.day.newtemplate
cat makefile.day.template >> makefile.day.newtemplate
echo "texheader   := $(pwd)/header.tex" > makefile.overall.newtemplate
cat makefile.overall.template >> makefile.overall.newtemplate

# Step 3: Search all READMEs, there we need the makefile and then execute make
find . -name "README.md" -exec dirname {}  \; | sort  > directories.temp

# Step 4: Copy makefiles to the directories found
while read DIRECTORY ; do cp makefile.chap.newtemplate "$DIRECTORY/makefile" ; done < directories.temp 


# Step 5: Search all level.day - Files  there we need the modified makefile 
find . -name "level.day" -exec dirname {}  \; | sort  > days

# Step 6: Copy makefiles to the directories found
while read DAY ; do cp makefile.day.newtemplate "$DAY/makefile" ; done < days

 
# Step 7: Overwrite top-level-makefile 
cp makefile.overall.newtemplate makefile 

# Step 8: change order of directory-levels : Grep away the days and append them at the end...
grep -v -x -f days directories.temp > directories
cat days >> directories
rm directories.temp 

# Step 9 : Cleanup
rm *.newtemplate

# Announce next steps 
echo "makefiles created"
echo "Either call generatedocs from here or go to the responsible directory and call make there"



